name: Deploy Landing Page

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files in workspace
        run: ls -la

      - name: List files in landing-page directory
        run: ls -la ./landing-page

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "./landing-page/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
          elif [ -f "./landing-page/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ./landing-page/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('landing-page/package-lock.json', 'landing-page/yarn.lock') }}-${{ hashFiles('landing-page/**/*.ts', 'landing-page/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('landing-page/package-lock.json', 'landing-page/yarn.lock') }}-

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.runner }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: ./landing-page

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
        working-directory: ./landing-page

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./landing-page/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
